/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductosIndexRouteImport } from './routes/productos/index'
import { Route as ProductosProductIdRouteImport } from './routes/productos/$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosIndexRoute = ProductosIndexRouteImport.update({
  id: '/productos/',
  path: '/productos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosProductIdRoute = ProductosProductIdRouteImport.update({
  id: '/productos/$productId',
  path: '/productos/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/productos/$productId': typeof ProductosProductIdRoute
  '/productos/': typeof ProductosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/productos/$productId': typeof ProductosProductIdRoute
  '/productos': typeof ProductosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/productos/$productId': typeof ProductosProductIdRoute
  '/productos/': typeof ProductosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/productos/$productId' | '/productos/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/productos/$productId' | '/productos'
  id: '__root__' | '/' | '/productos/$productId' | '/productos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductosProductIdRoute: typeof ProductosProductIdRoute
  ProductosIndexRoute: typeof ProductosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos/': {
      id: '/productos/'
      path: '/productos'
      fullPath: '/productos/'
      preLoaderRoute: typeof ProductosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos/$productId': {
      id: '/productos/$productId'
      path: '/productos/$productId'
      fullPath: '/productos/$productId'
      preLoaderRoute: typeof ProductosProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductosProductIdRoute: ProductosProductIdRoute,
  ProductosIndexRoute: ProductosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
